# Generated by Django 3.1 on 2020-10-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nome do igrediente'),
        ),
    ]
